language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm i
before_script:
  - npm prune
script:
  - npm run build
notifications:
  email: false